### ISSUE TITLE
Reproducible Builds

### ISSUE THREAD

**Issue by IzzySoft** [DanielRendox/RoutineTracker#28]
I've checked your app if its build is reproducible (see: [Reproducible Builds, special client support and more in our repo](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients)), but while I was able to successfully generate the APK using `./gradlew assembleRelease`, the differences to the one provided at your latest release were huge. Was that APK really built from the commit the tag points to? If so, did I miss some build options? And if not, which commit was it?

Here's the diff of the APKs:

```diff
-------------------------------
--- /dev/fd/63  2024-07-10 21:26:44.945211305 +0200
+++ /dev/fd/62  2024-07-10 21:26:44.949211280 +0200
@@ -6,8 +6,6 @@
   32-bit CRC value (hex):                         0dd916c9
   classes.dex
   32-bit CRC value (hex):                         189501a8
-  classes2.dex
-  32-bit CRC value (hex):                         1bdbf8e6
   DebugProbesKt.bin
   32-bit CRC value (hex):                         d5ac4dc2
   LICENSE-junit.txt
@@ -1976,9 +1974,3 @@
   32-bit CRC value (hex):                         88b2a3b0
   resources.arsc
   32-bit CRC value (hex):                         4ef866dc
```

As pointed out, the diff of the `classes2.dex` is rather huge. Or to be more precise: that file is not even present at all in our build. Your release was tagged on March 15th, but points to a commit from February 7th; maybe the APK was built from a later commit? If so, could you tell us from which?

We'd appreciate if you could help making your build reproducible. We've prepared some [hints on reproducible builds](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds) for that.

Looking forward to your reply!

**Comment by DanielRendox** [comment]
Hi, the fun thing is that I didn't even publish the app on IssyOnDroid, it was someone else who did that.

**Comment by IzzySoft** [comment]
Yeah, funny, who might have been so daring :see_no_evil: Maybe the Izzy, from IzzyOnDroid? :wink: And I hope you didn't mind? The license said I could.

Hope I could answer your question – looking forward to your answer to mine then :stuck_out_tongue_winking_eye: Thanks in advance!

**Comment by DanielRendox** [comment]
Ah, if only I knew about these things when releasing the app. I've built the APK from the commit the tag points to and compared it with the released version myself and I found out that it indeed misses `classes2.dex`. 

Honestly, I don't remember which commit it was built from. I only remember that I built the `v0.1.0` APK on February 7th and it's very likely I haven't changed it since then. The release was tagged on March 15th because I changed the name of the tag and the GitHub release name on that date.

Also, there are two flavors: `minSdk21` with `coreLibraryDesugaring` enabled and `minSdk26` where it is disabled. `./gradlew assembleRelease` generates two apks, one for each of those flavors. Since the difference in the APK size is insignificant, I currently use the APK for `minSdk21` in the releases. So we shouldn't take `minSdk26` into account.

If you have any ideas on how we could make this particular build reproducible, feel free to provide them. If not, I will try my best to not repeat this mistake in the next releases.

**Comment by IzzySoft** [comment]
> Ah, if only I knew about these things when releasing the app.

We were not even public with RB back then, so we could not have told you…

> Honestly, I don't remember which commit it was built from.

As the only diff is the missing `classes2.dex` and after what you wrote, it's most likely the commit the tag points to – but that I picked the wrong build flavor. I'm running it now with the `minSdk21` one to verify that… and: YES! That did the trick. Instead of `./gradlew assembleRelease` I've now used `./gradlew assembleMinSdk21Release`, and the app is RB, congrats! Shield will be up in a few minutes… Now. Welcome to the RB family! Here's your [welcome toot](https://floss.social/@IzzyOnDroid/113089396812625995):

![image](https://github.com/user-attachments/assets/607bc346-4128-4438-bb10-ac63cd696c63)

Now we just need to get Grocery Genius fixed again…
